# Generated by Django 5.2.16 on 2026-07-09 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_inicial', models.DecimalField(decimal_places=3, max_digits=5)),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=20)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inversiones.activo')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inversiones.portafolio')),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=4, max_digits=15)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inversiones.activo')),
            ],
        ),
    ]
