# Generated by Django 5.2.16 on 2026-07-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
