# Generated by Django 5.2.16 on 2026-07-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0002_alter_activo_nombre_alter_portafolio_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversion',
            name='cantidad',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
